NLRFIM-169 added support to AppSwitch
digst/OIOSAML.Net pull request #67
Opened 2023-04-25 12:39 UTC by achabala

2023-05-09 04:16 UTC, mdbech requested changes

2023-05-09 04:16 UTC, mdbech commented on src/dk.nita.saml20/dk.nita.saml20/Utils/AppSwitchSerialization.cs
> +        public static XmlElement ToXmlElement(this AppSwitch appSwitch, XmlDocument owner)
Why is it that the existing Serialization-class can't be used?

2023-05-09 04:16 UTC, mdbech commented on src/dk.nita.saml20/dk.nita.saml20/public-extensions-schema.xsd
> +﻿<?xml version="1.0" encoding="UTF-8" ?>
Place it in the "Schema"-folder.

2023-05-09 04:16 UTC, mdbech commented on src/dk.nita.saml20/dk.nita.test.saml20/Saml20/Protocol/HttpRedirectBindingTest.cs
> +            string request = string.Empty.PadLeft(350, 'A')+"������";
Are you sure about this changes?

2023-05-09 04:16 UTC, mdbech commented on src/dk.nita.saml20/dk.nita.test.saml20/app.config
> +    <AppSwitchReturnURL platform = "iOS">sp1.test-nemlog-in.dk</AppSwitchReturnURL>
```suggestion
    <AppSwitchReturnURL platform="iOS">sp1.test-nemlog-in.dk</AppSwitchReturnURL>

```

2023-05-09 04:16 UTC, mdbech commented on src/dk.nita.saml20/dk.nita.saml20/Config/AppSwitchReturnURL.cs
> +        public string Platform;
Why isn't this an enum value? Would make logic in the FindAppSwitchReturnUrlForPlatform-method simpler and the value is already suppose to be a known set of values.

I would discourage the use of string comparison in this situation.

2023-05-09 04:16 UTC, mdbech commented on src/dk.nita.saml20/dk.nita.saml20/Config/SAML20FederationConfig.cs
> +                x.Platform.Trim().ToLowerInvariant() == appSwitchPlatform.Trim().ToLowerInvariant())?.Value;
Suddently comparison is case insensitive.

2023-05-09 04:16 UTC, mdbech commented on Net SAML2 Service Provider Framework.docx
MitID not MyID.

2023-05-09 04:16 UTC, mdbech commented on Net SAML2 Service Provider Framework.docx
I'm missing documentation of the option of using the new HTTP request parameter appSwitchPlatform for the SignonHandler.

2023-05-11 08:22 UTC, mdbech requested changes

2023-05-11 08:22 UTC, mdbech commented on Net SAML2 Service Provider Framework.docx
Please re-upload, the file is damaged and can't be opened.

Peter had similar problem with the Java version, please check with him if you have problems.

2023-05-11 09:35 UTC, achabala commented on Net SAML2 Service Provider Framework.docx
done

2023-05-11 13:34 UTC, mdbech approved these changes

2023-05-11 14:07 UTC, merged